config/routes.rb
Rails.application.routes.draw do
  root "categories#index"

  resources :categories, only: [:show]
  resources :cart_items, only: [:update, :destroy, :create]

  get    "/cart", to: "cart_items#index"
  delete "/cart/destroy", to: "carts#delete"

  resources :users, only: [:create]
  resources :notifications, only: [:create]

  namespace :user do
    resources :orders, only: [:create, :index]
  end

  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin, only: [:show] do
    resources :categories, only: [:show, :index, :update]
    resources :items, only: [:create, :update]
    resources :orders, only: [:index]
  end

  resources :charges, only: [:new, :create]
end

app/models/cart_item.rb
class CartItem < SimpleDelegator
  attr_accessor :quantity
  def initialize(item, quantity=0)
    super(item)
    @quantity = quantity
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def create
    item           = Item.find(params[:item_id])
    item_quantity  = params[:quantity]
    @cart.add_item(item.id, item_quantity)
    session[:cart] = @cart.contents
    flash[:notice] = "You now have #{pluralize(@cart.count_of(item.id), item.title)}."
    redirect_to :back
  end

  def index
    @cart_items  = @cart.items
    @total_price = @cart.total_items_price(@cart_items)
  end

  def update
    @cart.contents[params[:id]] = params[:quantity].to_i
    redirect_to :back
  end

  def destroy
    @cart.contents.delete(params[:id])
    redirect_to :back
  end
end

app/views/cart_items/index.html.erb
<table>
  <thead>
    <tr>
      <th class="iphone_hide">Item</th>
      <th>Title</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total Price</th>
    </tr>
  </thead>
  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td rowspan="2" class="iphone_hide"><%= image_tag(cart_item.image.url, size: "800x800") %></td>
        <td><%= cart_item.title %></td>
        <td>
          <%= form_tag cart_item_path(cart_item.id), method: :put do %>
            <%= select_tag :quantity, options_for_select((1..10), cart_item.quantity) %>

            <%= button_tag(type: "submit", title: "Update Quantity", data: {tooltip: ""}, class: "refresh-icon") do %>
              <i class="fi-refresh"></i>
            <% end %>

            <%= link_to '<i class="fi-trash"></i>'.html_safe, cart_item_path(cart_item.id), method: :delete, title: "Delete Item", data: {tooltip: ""} %>
          <% end %>
        </td>

        <td>&#36;<%= "%.2f" % cart_item.price %></td>
        <td>&#36;<%= "%.2f" % (cart_item.price * cart_item.quantity) %></td>
      </tr class="iphone_hide">
        <td colspan="4"><%= cart_item.description %></td>
      <tr class="iphone_hide">
        <td colspan="5"></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="2" class="iphone_hide"></td>
      <td colspan="1" class="iphone_show"></td>
      <td><%= button_to "Clear Cart", cart_destroy_path, method: :delete, class: "tiny button radius" %></td>
      <td>
        <% if current_user %>
          <%=button_to "Checkout", user_orders_path, params: {total_price: @total_price }, class: "tiny button radius" %>
        <% else %>
         <a href="/login" data-reveal-id="LoginModal"><u>Login</u></a>
        <% end %>
      </td>
      <td class="price">&#36;<%= "%.2f" % @total_price %></td>
    </tr>
  </tbody>
</table>