config/routes.rb
Rails.application.routes.draw do
  root "categories#index"

  resources :categories, only: [:show]
  resources :cart_items, only: [:update, :destroy, :create]

  get    "/cart", to: "cart_items#index"
  delete "/cart/destroy", to: "carts#delete"

  resources :users, only: [:create]
  resources :notifications, only: [:create]

  namespace :user do
    resources :orders, only: [:create, :index]
  end

  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin, only: [:show] do
    resources :categories, only: [:show, :index, :update]
    resources :items, only: [:create, :update]
    resources :orders, only: [:index]
  end

  resources :charges, only: [:new, :create]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_items
  has_many :items, through: :category_items

  validates :name, presence: true, uniqueness: true

  has_attached_file :image, default_url: "Fresh-Fruit-Stand.jpg"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all
  end

  def show
    category = Category.find(params[:id])
    @category_items = category.items
  end

  def update
    category = Category.find(params[:id])

    if category.items.any? { |item| item.available? }
      category.items.each do |item|
        item.update!(available: false)
      end
      flash[:notice] = "You've successfully retired #{category.name}."
      redirect_to :back
    else
      category.items.each do |item|
        item.update!(available: true)
      end
      flash[:notice] = "You've successfully un-retired #{category.name}."
      redirect_to :back
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    category = Category.find(params[:id])
    @category_items = category.items

    if category.items.all? { |item| item.available? == false }
      flash[:error] = "This Category Is Empty, Nice Try!"
      redirect_to :root
    end
  end
end

app/views/admin/categories/_admin_update_create_modals.html.erb
<div id="AdminAddsItemModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <%= form_for(:item, url: admin_items_path, html: {multipart: true}) do |f| %>
    <h3>Add Item</h3><br>
    <%= f.text_field :title %>
    <%= f.text_field :description %>
    <%= f.text_field :price %>
    <%= f.file_field :image %>
    <%= f.collection_select :category, Category.all, :id, :name, prompt: true, include_blank: "New Category" %>
    <div class="hidden_input_field" id="hif">
     <%= f.file_field :category_image %>
     <%= f.text_field :new_category, label: "New Category Name" %>
    </div>
    <%= f.submit "Add Item" %>
  <% end %>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/admin/categories/index.html.erb
<div class="row">
  <div class="medium-12 columns">
    <div class="row">
      <%= image_tag("giv-rasberries.jpg", class: "medium-12 columns") %>
    </div>
  </div>
</div>

<hr/>

<div class="row">
  <% @categories.each do |category| %>
    <div class="medium-4 columns image_rapper">
      <%= image_tag(category.image.url, class: "cat_image") %>
      <div class="text_title"><%= link_to category.name, admin_category_path(category.id), class: "category_title_text" %></div>

      <% category.items.any? { |item| item.available? } ? status = "Retire" : status = "Un-Retire" %>
      <%= link_to status, admin_category_path(category.id), method: :put, class: "button round tiny" %>
    </div>
  <% end %>
</div>

<%= render "admin/categories/admin_update_create_modals" %>

app/views/admin/categories/show.html.erb
<div class="row">
  <% @category_items.each do |item| %>
    <div class="card medium-3 columns">
        <%= image_tag(item.image.url, class: "item_image") %>
          <div class="card-divider">
            <h6><b><%= item.title %></b></h6>
          </div>
          <div class="card-section">
            <p><%= item.description %></p>
            <h6>&#36;<%= "%.2f" % item.price %></h6>
          </div>
          <a href="" data-reveal-id="Update-item-<%= item.id %>" class="tiny button radius">Update</a>
      </div>

    <div id="Update-item-<%= item.id %>" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
          <%= form_for(:item, url: admin_item_path(item.id), method: :put, html: {multipart: true}) do |f| %>
            <h3>Update Item</h3><br>
            <%= f.text_field :title, value: item.title %>
            <%= f.text_field :description, value: item.description %>
            <%= f.text_field :price, value: item.price %>
            <%= f.file_field :image %>
            <%= f.select :available, [true, false], label: "Available In Store?" %><br>
            <%= f.submit "Update Item" %>
          <% end %>
          <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>
  <% end %>
</div>

<%= render "admin/categories/admin_update_create_modals" %>