config/routes.rb
Rails.application.routes.draw do
  root "categories#index"

  resources :categories, only: [:show]
  resources :cart_items, only: [:update, :destroy, :create]

  get    "/cart", to: "cart_items#index"
  delete "/cart/destroy", to: "carts#delete"

  resources :users, only: [:create]
  resources :notifications, only: [:create]

  namespace :user do
    resources :orders, only: [:create, :index]
  end

  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin, only: [:show] do
    resources :categories, only: [:show, :index, :update]
    resources :items, only: [:create, :update]
    resources :orders, only: [:index]
  end

  resources :charges, only: [:new, :create]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_items
  has_many :items, through: :category_items

  validates :name, presence: true, uniqueness: true

  has_attached_file :image, default_url: "Fresh-Fruit-Stand.jpg"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all
  end

  def show
    category = Category.find(params[:id])
    @category_items = category.items
  end

  def update
    category = Category.find(params[:id])

    if category.items.any? { |item| item.available? }
      category.items.each do |item|
        item.update!(available: false)
      end
      flash[:notice] = "You've successfully retired #{category.name}."
      redirect_to :back
    else
      category.items.each do |item|
        item.update!(available: true)
      end
      flash[:notice] = "You've successfully un-retired #{category.name}."
      redirect_to :back
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    category = Category.find(params[:id])
    @category_items = category.items

    if category.items.all? { |item| item.available? == false }
      flash[:error] = "This Category Is Empty, Nice Try!"
      redirect_to :root
    end
  end
end

app/views/categories/index.html.erb
<div class="row">
 <div id="banner-image"></div>
</div>

<hr>

<div class="row">
  <% @categories.each do |category| %>
    <% if category.items.any? { |item| item.available? } %>
      <div class="medium-4 columns image_rapper">
        <%= image_tag(category.image.url, class: "cat_image") %>

        <div class="text_title"><%= link_to category.name, category_path(category.id), class: "category_title_text" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="row">
  <% @category_items.each do |item| %>
    <% if item.available? %>
      <div class="card medium-3 columns">
        <%= image_tag(item.image.url, class: "item_image") %>
          <div class="card-divider">
            <h6><b><%= item.title %></b></h6>
          </div>
          <div class="card-section">
            <p><%= item.description %></p>
            <h6>&#36;<%= "%.2f" % item.price %></h6>
            <%= form_tag cart_items_path, method: :post do %>
              <%= select_tag :quantity, options_for_select(1..10) %>
              <%= hidden_field_tag :item_id, item.id %>
              <%= submit_tag "Add To Cart", class: "tiny button radius" %>
            <% end %>
          </div>
      </div>
    <% end %>
  <% end %>
</div>