config/routes.rb
Rails.application.routes.draw do
  root "categories#index"

  resources :categories, only: [:show]
  resources :cart_items, only: [:update, :destroy, :create]

  get    "/cart", to: "cart_items#index"
  delete "/cart/destroy", to: "carts#delete"

  resources :users, only: [:create]
  resources :notifications, only: [:create]

  namespace :user do
    resources :orders, only: [:create, :index]
  end

  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin, only: [:show] do
    resources :categories, only: [:show, :index, :update]
    resources :items, only: [:create, :update]
    resources :orders, only: [:index]
  end

  resources :charges, only: [:new, :create]
end

app/views/layouts/_login_register_modals.html.erb
<div id="LoginModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
    <%= form_for(:session, url: login_path) do |f| %>
      <h3>Login</h3><br>
      <%= f.text_field :username %>
      <%= f.text_field :password, type: "password"%>
      <%= f.submit "Login" %>
    <% end %>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
  <h6>Not Registered? <a href="/users" data-reveal-id="RegisterModal"><u>Register</u></a></h6>
</div>

<div id="RegisterModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
    <%= form_for(:user, url: users_path) do |f| %>
      <h3>Register</h3><br>
      <%= f.email_field :email_address, label: 'E-mail' %>
      <%= f.text_field :username %>
      <%= f.text_field :password, type: "password" %>
      <%= f.text_field :password_confirmation, type: "password" %>
      <%= f.submit "Create Account" %>
    <% end %>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/layouts/_navbar.html.erb
<% if current_admin? %>
  <div class="row navbar">
  <div class="medium-6 columns">
    <%= link_to "ADMIN", admin_categories_path, class: "logo-text-link left" %>
  </div>

    <div class="medium-6 columns">
      <ul class="inline-list right">
        <li><a data-method="delete" href="/logout">Logout</a></li>
        <li><a href="/admin/orders">Orders</a></li>
        <li><a href="/admin/items/new" data-reveal-id="AdminAddsItemModal">Add Items</a></li>
      </ul>
    </div>
  </div>
<% elsif current_user %>
  <div class="row navbar">
    <div class="medium-5 columns">
      <%= link_to "Fruits For Humanity", root_path, class: "logo-text-link left" %>
    </div>
    <div class="medium-2 columns">
      <a href="/"><%= image_tag("apple-icon-32-px-orange.png", id: "apple-icon") %></a>
    </div>

    <div class="medium-5 columns">
      <ul class="inline-list right">
        <li><a href="/notifications" data-reveal-id="NotificationModal">Contact</a></li>
        <li><a data-method="delete" href="/logout">Logout</a></li>
        <li><span data-tooltip aria-haspopup="true" class="tip-bottom radius" data-options="disable_for_touch:false" title="Fruits For Humanity is a non-profit organization. All proceeds go to charities that feed the hungry.">About</span></li>
          <% if !current_admin? %>
            <li><a href="/user/orders">My Orders</a></li>
          <% end %>
        <% if @cart.contents.empty? %>
          <li><span data-tooltip aria-haspopup="true" class="tip-bottom radius carts" title="Your Cart Is Empty"><a><i class="fi-shopping-cart"></i></a></span></li>
        <% else %>
          <li><%= link_to '<i class="fi-shopping-cart"></i>'.html_safe, cart_path, title: @cart.count_all.to_s + " Item(s)", data: {tooltip: ""}, :class => "tip-bottom radius carts" %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% else %>
<div class="row navbar">
    <div class="medium-5 columns">
      <%= link_to "Fruits For Humanity", root_path, class: "logo-text-link left" %>
    </div>
    <div class="medium-2 columns">
      <a href="/"><%= image_tag("apple-icon-32-px-orange.png", id: "apple-icon") %></a>
    </div>
    <div class="medium-5 columns">
      <ul class="inline-list right">
        <li><span data-tooltip aria-haspopup="true" class="tip-bottom radius" data-options="disable_for_touch:false" title="Fruits For Humanity is a non-profit organization. All proceeds go to charities that feed the hungry.">About</span></li>
        <li><a href="/users" data-reveal-id="RegisterModal">Register</a></li>
        <li><a href="/login" data-reveal-id="LoginModal">Login</a></li>
        <% if @cart.contents.empty? %>
          <li><span data-tooltip aria-haspopup="true" class="tip-bottom radius carts" title="Your Cart Is Empty"><i class="fi-shopping-cart"></i></span></li>
        <% else %>
          <li><%= link_to '<i class="fi-shopping-cart"></i>'.html_safe, cart_path, title: @cart.count_all.to_s + " Item(s)", data: {tooltip: ""}, :class => "tip-bottom radius carts" %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= render "layouts/login_register_modals" %>
<%= render "layouts/notification_email_modal" %>

app/views/layouts/_notification_email_modal.html.erb
<div id="NotificationModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
    <%= form_for(:notification, url: notifications_path) do |f| %>
      <%= f.email_field :email_address %>
      <%= f.text_field :name %>
      <%= f.text_field :message %>
      <%= f.submit "Send Email" %>
    <% end %>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Fruits For Humanity" %></title>

    <%= stylesheet_link_tag    "application", "//fonts.googleapis.com/css?family=Lily+Script+One" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="flash-puppies"><%= display_flash_messages %></div>
    <%= yield %>
  </body>
</html>